### ISSUE TITLE
Suggestions for greater usability

### ISSUE THREAD

**Issue by tytell** [tsipkens/atems#49]
https://github.com/tsipkens/atems/blob/cd661f02c5b7a3c95215f084e4064a0f7acd4203/main_0.m#L16

- Change "more particles or add to existing particles" button to be labeled something like "Interactive tool to adjust thresholding"
  - Adjusting the "slider" does not seem to offer any feedback on how it is changing the threshold. That makes it very hard to judge whether the change is sufficient. I suggest overlying a color that shows the thresholded region.
  - I'm not sure if I'm doing it incorrectly, but every time I adjust the slider, I get a black image afterward, suggesting that the threshold is incorrect
  - There does not seem to be a way to go back in the steps. That would be helpful
  - Now I see that "Add (to) aggregates" button is sort of like a "start over" option. It is unclear what that actually does

**Comment by tsipkens** [comment]
- The "slider" appears to be working in the Windows version, but the output was quite subtle. An update is forthcoming to add a colored overlay as a result of adjusting the slider. 
- There was also a previous update that added a textbox for updating the slider using a number instead of by dragging the slider itself. This should improve selecting a a level. 
- The cancel button is used to reset the GUI. Then one can add more particles. The button to add to the binary mask was updated accordingly. 
- Errors could be associated with skipping the lasso step. While this is okay in general, it is less effective when refining a binary mask. Communicating this in the app would clutter the interface and so was not changed.

**Comment by tsipkens** [comment]
Issues are partially resolved, as per the previous comment, with some minor caveats around further improvements. The name on the button was changed in the commit: https://github.com/tsipkens/atems/commit/9c79149975924f43c26611972dbd5be4ad024782.

**Comment by tsipkens** [comment]
Help buttons have also been added to the GUI to aid in understanding common issues with the app.
